# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4986703b7b4ffeddbeb13d103f9e6b3cc8e182675e076b0335d6ad024619060eb2e0db3e6fdf6d1c5528a51abd75fb2d78be896c59f7f783e6e8b13d3bce0e37

test:
  secret_key_base: 036d238a4e3783b01d7a129809136601c5e44e24cae4341682a455025422baae845b8070b78c9ab0aa48fd9538aec2ae46b1bdbb5da1318da77a83914c390987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
